FROM ubuntu:18.
FROM openjdk:8u191-jre-alpine3.8
RUN apk add --no-cache curl tar bash procps
ARG MAVEN_VERSION=3.6.3
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
# Install Java.
#
#RUN apk --update --no-cache add openjdk8 curl

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
 && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
 && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
 && rm -f /tmp/apache-maven.tar.gz \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV CLASSPATH /usr/lib/jvm/java-1.8-openjdk/lib

# Define default command.
CMD ["mvn", "--version"]

WORKDIR E:/Advanced_Selenium_Test_Automation_Framework-master
COPY target/AdavencedLevel.QDPM-0.0.1-SNAPSHOT.jar AdavencedLevel.QDPM-0.0.1-SNAPSHOT.jar
COPY target/AdavencedLevel.QDPM-0.0.1-SNAPSHOT-tests.jar AdavencedLevel.QDPM-0.0.1-SNAPSHOT-tests.jar
COPY target/libs libs
COPY config.properties config.properties
COPY testng.xml testng.xml
COPY TaskCreationTestData.xlsx TaskCreationTestData.xlsx
#ENTRYPOINT ["java","-jar","/E:/Advanced_Selenium_Test_Automation_Framework-master/AdavencedLevel.QDPM-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
ENTRYPOINT java -cp AdavencedLevel.QDPM-0.0.1-SNAPSHOT.jar;AdavencedLevel.QDPM-0.0.1-SNAPSHOT-tests.jar;libs/* org.testng.TestNG testng.xml